version: '2'

services:
  celery_cron_job:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      COMPOSE_HTTP_TIMEOUT: 300
      SQLALCHEMY_DATABASE_URI: mysql://admin:G90ok0lSTz8i@db.prod.coincube.io/coincube
      CELERY_BROKER_URL: redis://redis-cron-job.prod.coincube.io:6379/0
      EXAPI_URL: http://exapi:9000
      EMAIL_URL: http://email:9090
    command: >
      /opt/conda/bin/celery worker
      --app celery_update
      --hostname %h-%n
      --loglevel DEBUG
      --concurrency 10
    networks:
      back:

  celery_scheduler:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      COMPOSE_HTTP_TIMEOUT: 300
      SQLALCHEMY_DATABASE_URI: mysql://admin:G90ok0lSTz8i@db.prod.coincube.io/coincube
      CELERY_BROKER_URL: redis://redis-cron-job.prod.coincube.io:6379/0
      EXAPI_URL: http://exapi:9000
      EMAIL_URL: http://email:9090
    command: >
      /opt/conda/bin/celery
      -A celery_update beat
      --loglevel DEBUG
    networks:
      back:

networks:
  back:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.22.0/24